# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
export LANG=en_US.UTF-8 ncmpcpp
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/asuka/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# infinality (Kori)
#export INFINALITY_FT_FILTER_PARAMS='25 30 40 30 25'
#export INFINALITY_FT_FILTER_PARAMS='15 25 45 25 15'
#export INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH=0
#export INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH=0
#export INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS=true
#export INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT=0
#export INFINALITY_FT_GAMMA_CORRECTION='0 100'
#export INFINALITY_FT_BRIGHTNESS=0
#export INFINALITY_FT_CONTRAST=0
#export INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH=5
#export INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH=0
#export INFINALITY_FT_FRINGE_FILTER_STRENGTH=0
#export INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH=10
#export INFINALITY_FT_STEM_ALIGNMENT_STRENGTH=0
#export INFINALITY_FT_STEM_FITTING_STRENGTH=25
#export INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE=50
#export INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS=true
#export INFINALITY_FT_USE_VARIOUS_TWEAKS=true
