#! /bin/sh

FG="#95A7CC"

bspc config border_width         0
bspc config window_gap          40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config focused_border_color "$FG"
bspc config active_border_color "$FG"
bspc config normal_border_color "$FG"
bspc config presel_border_color "$FG"
bspc config focused_locked_border_color "$FG"
bspc config active_locked_border_color "$FG"
bspc config normal_locked_border_color "$FG"
bspc config focused_sticky_border_color "$FG"
bspc config active_sticky_border_color "$FG"
bspc config normal_sticky_border_color "$FG"
bspc config focused_private_border_color "$FG"
bspc config active_private_border_color "$FG"
bspc config normal_private_border_color "$FG"
bspc config urgent_border_color "$FG"
bspc config top_padding 15

#bspc monitor VGA1 -d 1 2 3 4 5
#bspc monitor LVDS1 -d 6 7 8 9 10

bspc rule -a Screenkey manage=off
bspc rule -a gimp floating=on
bspc rule -a Steam floating=on
bspc rule -a PlayOnLinux desktop=^3
bspc rule -a termite desktop=^2

vgamoncheck
laptopmoncheck

#$HOME/.config/bspwm/captain
